#!/usr/bin/env python3
# Copyright 2019 Philip Cronje
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
import argparse
import boto3
import datetime
import os
import time

parser = argparse.ArgumentParser()
parser.add_argument("-p", "--path", default="/srv/elasticraft")
parser.add_argument("-r", "--region", required=True)
arguments = parser.parse_args()

cloudwatch = boto3.client("cloudwatch", region_name=arguments.region)

while True:
    fs_stat = os.statvfs(arguments.path)
    blocks_used = fs_stat.f_blocks - fs_stat.f_bavail
    percent_used = float(blocks_used) / fs_stat.f_blocks * 100
    cloudwatch.put_metric_data(Namespace="Elasticraft", MetricData=[{
        "MetricName": "DataVolumeSpaceUsedPercent", "Timestamp": datetime.datetime.now(),
        "Value": percent_used, "Unit": "Percent"}])
    time.sleep(30)
